name: 'Repo Level Trivy Scan'

on:
  pull_request:
  schedule:
    # Runs daily at 4 AM UTC (11 PM CDT / 12 AM EDT)
    - cron: '*/15 * * * *'

jobs:
  # JOB 1: Build the Docker image for the Python agent and push it to GHCR
  build:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push images to GHCR

    outputs:
      image-name: ${{ steps.set-image-name.outputs.image-name }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Log in to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- This section is now tailored for a Python project ---
      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          # Adjust this version to match your project's requirements
          python-version: '3.11'
      
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # --------------------------------------------------------

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v6
        with:
          # Assumes the Dockerfile is in the root directory
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: 'Set image name output'
        id: set-image-name
        run: echo "image-name=ghcr.io/${{ github.repository }}:${{ github.sha }}" >> $GITHUB_OUTPUT

  # JOB 2: Call the reusable organization workflow (No changes here)
  scan:
    name: 'Trigger Organization Scan'
    needs: build
    permissions:
      contents: read
      packages: read
      security-events: write # Required to allow the called workflow to upload SARIF results
    uses: newrelic-trivy/.github/.github/workflows/org-level-trivy-scan.yml@main
    with:
      image-name: ${{ needs.build.outputs.image-name }}
    secrets: inherit
